### PR TITLE
Fluorescent reporters

### PR DESCRIPTION
**Pull request by vinoo-igem**
A start to a fluorescent reporter library, containing 4 of the iGEM Registry's most used fluorescent reporter proteins along with 4 IP-Free ones from the BioBricks Foundation. As a starting point, this selection is not to be the most useful reporters (ex: selection based on spectral overlap). E0040-E1010-E0030-E0020 may be better only for historical purposes with others as recommended for use.

### CODE REVIEW

**Review by jakebeal — CHANGES_REQUESTED** [review]
Looks like a good initial set; I think we may want some additional colors later, and to make sure that it covers all of the Engineering Committee recommended proteins.

**Comment by vinoo-igem** [comment]
Working on this today, and a curation/sequence issue has popped up.

BBa_E0040 (labelled as GFPmut3b SwissProt: P42212) DNA seq results in the the first three AA as: MRK

GFPmut3b SwissProt: P42212 on fpbase and uniprot is: MSK
https://www.fpbase.org/protein/gfpmut3/
https://www.uniprot.org/uniprot/P42212

The S2R change is the only mutation and is described on the documentation page of BBa_E0040, as one that should have no effect: http://parts.igem.org/Part:BBa_E0040:Design

But it raises the question (along with other big ones), on how should we proceed. For now I suggest adding in both sequences as two separate parts in the collection to acknowledge the difference, and prior/during the review of actual synthesis ordering, decide on what's best (order both, order the "correct" GFPmut3b, etc)  

I expect similar issues to pop up, so maybe we should open a separate issue about this to discuss?

**Comment by jakebeal** [comment]
Agreed; I don't think it needs to block the merge, but it should be noted and tracked so we can revisit it and decide what do to about it.

**Comment by vinoo-igem** [comment]
Not sure what the correct process is here, but wanted to push the changes even though it should not be merged.

Some questions I had. We have FPs tied to AA sequences on GenBank, what do we want to do about the DNA sequence we order if we cannot find a suitable DNA sequence on GenBank for _E. coli_ 

Also, what should I do about adding new organisms to the list?

**Comment by jakebeal** [comment]
Pushing changes when you've got updates is entirely appropriate; GtiHub lets me know what's new since last I looked.

With regards to the AA question --- I think that's a very good question to open an issue for discussion on, and doesn't need to be resolved for this first pull request. 

In terms of adding new organisms to the list --- this is something for which adding terms to the organism sheet is fine, so I should update the readme.

**Review by jakebeal — APPROVED** [review]

**Review by vignoni — COMMENTED** [review]
I generally approve, but @vinoo-igem raises a good point. Two things from the top of my head:

- About fpbase, we need to be careful because for example the spectra for GFPmut3b were uploaded by our 2018 Valencia_UPV iGEM team, and they were obtained with the MRK version, however, I think the data in fpbase is from the paper and based on MSK.
- Again, I think we need to point to a DNA seq, not a AA (for how the protein works, there is no problem, but for how it gets expressed in an organism there is).

**Pull request merged**
