### PR TITLE
Create Plant package package excel/structure

### PR DESCRIPTION
**Pull request by nickdelkis**
Create package excel for others to build upon. Already contains some promoters found in the registry (35S, MAS, PDF1.2, BS3) , as well as At U6 for gRNA expression and hph CDS for hygromycin selection.

### CODE REVIEW

**Comment by nickdelkis** [comment]
Some iGEM parts were supposedly successfuly retrieved, but appear as _missing sequence_ in the final readme. Did I do something wrong @jakebeal ?

> Importing parts for package Plant Parts
Package specification contains 7 parts
Found 7 parts cached in package design files
 0 have sequences in Excel, 3 found in directory, 4 not found
 4 parts in directory are not used in package
 Found 4 unused parts:https://synbiohub.org/public/igem/BBa_K1467102 https://synbiohub.org/public/igem/BBa_K1467101 https://synbiohub.org/public/igem/BBa_K1467104 https://synbiohub.org/public/igem/BBa_K1467103
Attempting to download missing parts
Attempting to retrieve 4 parts from iGEM
Attempting to retrieve iGEM SBOL from SynBioHub: https://synbiohub.org/public/igem/BBa_BBa_K1467101
Attempting to retrieve iGEM SBOL from SynBioHub: https://synbiohub.org/public/igem/BBa_K1467101
  Successfully retrieved from SynBioHub
Attempting to retrieve iGEM SBOL from SynBioHub: https://synbiohub.org/public/igem/BBa_BBa_K1467102
Attempting to retrieve iGEM SBOL from SynBioHub: https://synbiohub.org/public/igem/BBa_K1467102
  Successfully retrieved from SynBioHub
Attempting to retrieve iGEM SBOL from SynBioHub: https://synbiohub.org/public/igem/BBa_BBa_K[146](https://github.com/iGEM-Engineering/iGEM-distribution/runs/5089318649?check_suite_focus=true#step:7:146)7103
Attempting to retrieve iGEM SBOL from SynBioHub: https://synbiohub.org/public/igem/BBa_K1467103
  Successfully retrieved from SynBioHub
Attempting to retrieve iGEM SBOL from SynBioHub: https://synbiohub.org/public/igem/BBa_BBa_K1467104
Attempting to retrieve iGEM SBOL from SynBioHub: https://synbiohub.org/public/igem/BBa_K1467104
  Successfully retrieved from SynBioHub
Retrieved 4 iGEM SBOL2 records from SynBioHub, writing to /home/runner/work/iGEM-distribution/iGEM-distribution/Plant Parts/iGEM_SBOL2_imports.xml
Attempting to retrieve 0 parts from SynBioHub
Retrieved 4 out of 4 missing sequences

**Comment by jakebeal** [comment]
@nickdelkis Looking at the Excel sheet, it looks like on the libraries page the parts are marked as not being final products, and thus not to be added to the distribution.

**Comment by nickdelkis** [comment]
Thanks for noting Jake, I made the dir in a rush and didn't wait to check the outcome. I changed False --> True and waiting to see if this changes things. However, the missing sequence error should not be linked (?)

**Comment by jakebeal** [comment]
That is odd... it looks like another instance of the same naming issue we're dealing with in #182 ?

**Comment by nickdelkis** [comment]
`missing_sequence` is haunting me!!! I will try to download the parts and import them as fasta to see if this will change things (well ... it ought)

**Comment by nickdelkis** [comment]
Working on #206 , I think that the problem with the names here is that part name is not identical to the part name in the registry. I will do everything locally for now and see if things work!

**Comment by nickdelkis** [comment]
> Expanding package build plan Plant Parts
Package contains 4 products: 4 libraries, 0 composites, and 0 individual parts
Error: Process completed with exit code 1.

I believe I've done everything according to other successful packages (fluorescent proteins, TetR orthologs) but an error is produced while creating vector plans. Does it maybe have to do with the unchecked flanking sequences that we use? (UTR, terminator) @jakebeal @vinoo-igem

**Comment by jakebeal** [comment]
It looks like something is not connecting correctly in the names in the library declaration: it should be getting caught earlier and with a clearer error, which I've filed a bug for.

**Comment by nickdelkis** [comment]
It likely has to do either with having several libraries (which has been done in other packages) or with the specific parts we added today (which produce no errors now), as the package could be completed with the four parts I initially imported. 

My last tries will be to remove the libraries one by one and see if one of them breaks the vector build, and go from there. Unsure if I can make the deadline though as I'm a bit drained from may hours of looking at .gb files! haha

**Comment by jakebeal** [comment]
If you aren't able to resolve it on your own, I can take a look at things in a few hours.

**Comment by nickdelkis** [comment]
I removed two of the four libraries, and now it produces an actual error! Hope I can debug or help you help me :) 
>File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/sbol_utilities/expand_combinatorial_derivations.py", line 84, in derivation_to_collection
    values = [id_sort(self.cd_variable_values(v)) for v in id_sort(cd.variable_features)]
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/sbol_utilities/expand_combinatorial_derivations.py", line 84, in <listcomp>
    values = [id_sort(self.cd_variable_values(v)) for v in id_sort(cd.variable_features)]
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/sbol_utilities/expand_combinatorial_derivations.py", line [58](https://github.com/iGEM-Engineering/iGEM-distribution/runs/5145113489?check_suite_focus=true#step:8:58), in cd_variable_values
    sub_cd_collections = [self.derivation_to_collection(d.lookup()) for d in id_sort(v.variant_derivations)]
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/sbol_utilities/expand_combinatorial_derivations.py", line 58, in <listcomp>
    sub_cd_collections = [self.derivation_to_collection(d.lookup()) for d in id_sort(v.variant_derivations)]
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/sbol_utilities/expand_combinatorial_derivations.py", line 84, in derivation_to_collection
    values = [id_sort(self.cd_variable_values(v)) for v in id_sort(cd.variable_features)]
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/sbol_utilities/expand_combinatorial_derivations.py", line 84, in <listcomp>
    values = [id_sort(self.cd_variable_values(v)) for v in id_sort(cd.variable_features)]
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/sbol_utilities/helper_functions.py", line 21, in id_sort
    return sorted(i, key=lambda x: x.identity if isinstance(x, sbol3.Identified) else x)
TypeError: '<' not supported between instances of 'str' and 'NoneType'
Error: Process completed with exit code 1.

**Pull request merged**
