### PR TITLE
Update README.md

### LINKED ISSUE #4: Clarify that Library & Composite = Build
Need to clarify the purpose of the library & composite spreadsheet in the README, explaining that it's how we do the build planning.  Point to the anderson library example as an example.
Also explain the "final product" column

### PR DESCRIPTION
**Pull request by jakebeal**
Add more explanation of branching, the Libraries & Composites sheet as a "build plan"

Fixes #4 and #5

### CODE REVIEW

**Comment by vinoo-igem** [comment]
I like the doc changes! But I do want to be a bit careful here with the spreadsheet <-> documentation, to avoid confusion and to also have consistency with the Registry: so thoughts on changing the Basic Parts tab (and accompanying documentation) to just Parts or Parts/Devices. 

I don't think we lose anything by removing "Basic" from there if the documentation explains it as: 

> In this context, "Parts" just means any contiguous DNA sequence that you don't need to subdivide, and can include multiple sequence features.

**Review by vinoo-igem — CHANGES_REQUESTED** [review]
Sorry, still getting used to this: I like the doc changes! But I do want to be a bit careful here with the spreadsheet <-> documentation, to avoid confusion and to also have consistency with the Registry: so thoughts on changing the Basic Parts tab (and accompanying documentation) to just Parts or Parts/Devices. 

I don't think we lose anything by removing "Basic" from there if the documentation explains it as: 

> In this context, "Parts" just means any contiguous DNA sequence that you don't need to subdivide, and can include multiple sequence features.

**Comment by jakebeal** [comment]
I'd like to propose to address the sheet name change via a separate issue and separate pull request, since it will also involve updating the spreadsheets and automation. I've opened #8 for this. Let me know if you're OK with approving all the rest to merge and separating the rename. I'll need to do that quickly, however, since we don't want to have lots of copies of the spreadsheet with the wrong name in them.

**Review by vignoni — APPROVED** [review]
Great. I approve, taking into account Naming issue is treated separately.

**Comment by jakebeal** [comment]
Thanks, @vignoni ; I'll wait for @vinoo-igem to weigh in as well before merging.

**Review by vinoo-igem — APPROVED** [review]

**Comment by vinoo-igem** [comment]
> I'd like to propose to address the sheet name change via a separate issue and separate pull request, since it will also involve updating the spreadsheets and automation. I've opened #8 for this. Let me know if you're OK with approving all the rest to merge and separating the rename. I'll need to do that quickly, however, since we don't want to have lots of copies of the spreadsheet with the wrong name in them.

That makes sense to me.

**Pull request merged**
