### PR TITLE
import of open yeast collection

### PR DESCRIPTION
**Pull request by jakebeal**
Now that #77 is resolved, I adjusted the imports for the Open Yeast materials to follow the implementation that I have set up.  I also set it up to include everything in the collection, though we still need to figure out how to deal with the fact that the parts are already embedded in plasmids. Do we want to just use them as-is, or resynthesize?

In doing so, I discovered one unexpected new issue: the ScARS_CEN part (BBF10K_000464) has in incorrect GenBank file associated with it: the GenBank that downloads declares that it is for Sc-pAdh1 (BBF10K_000034).
Right now, it's just showing up as "missing sequence", since I'm not sure how to resolve this. @noahsprent , if you're able to get an actual sequence for it to either paste or as a valid GenBank file to add into the directory, we can use that instead.

### CODE REVIEW

**Comment by jakebeal** [comment]
Got all the build bugs worked out; it's now in a good state for review, deferring the vector question for later.

**Review by vinoo-igem — APPROVED** [review]
All good, but of course didn't review the gb files aside from spot checking.

**Comment by jakebeal** [comment]
Thank you for spot-checking. And yes, there may indeed be some issues in the curation of these sequences, as noted above.  I'm going to wait for @noahsprent to comment as well before merging.

**Comment by vinoo-igem** [comment]
> though we still need to figure out how to deal with the fact that the parts are already embedded in plasmids. Do we want to just use them as-is, or resynthesize?

As for this, it's an open discussion. I've chatted with Noah a bit, and currently I'm leaning towards using them as-is for now. With a goal of us wanting to put together a group that helps add to and evolve this collection in the future. Some pros and cons I've thought of:

Pros
1. It's a complete collection: iGEMers who use this should be able to use everything within the collection to start a yeast project
2. Level 0s for building up a L1 device match other Type IIS standards. (Although not having done yeast work before, is the kozak seq, normally packaged with the promoter?)
3. Saves time, money, and synthesis budget

Cons
1. Compatibility with other Type IIS standards beyond Level 0s. Point 2 above, I can do some digging to check for compatibility with Loop assembly plasmids and others at well.
2. The parts aren't in pSB1C3 rather pOpen_v3 (pSB1A3 derived)

**Comment by noahsprent** [comment]
Hi both, sorry I was on holiday last week.

@jakebeal - Good spot! I have the sequence for the whole plasmid, and I can add it in the same way that I added the sequences for the plasmids with missing genbank files on FreeGenes. I've created #114, but not sure if I've done something wrong as it's failing checks. Definitely the best way to do this is for FreeGenes to update their GenBank files, but for now hopefully this is good enough. I could ask Scott if he has the Genbank files and we could bypass import from FreeGenes, but again seems better for them to make sure that they have them.

@vinoo-igem - That's a good summary, agreed about including the kit as-is for now. No need to pay for re-synthesis unless we want to make changes beyond just the vector.

**Review by noahsprent — APPROVED** [review]
Looks good to me after adding the correct sequence for BBF10K_000464

**Comment by jakebeal** [comment]
We've got pending work still with OpenYeast, but this can be safely merged in its current state. I've opened a new issue to track the remaining challenges (#122)

**Pull request merged**
