### PR TITLE
Additional cas13a

### PR DESCRIPTION
**Pull request by GC-repeat**
- E.coli codon optimized version of LwCas13 with and without purification and solubility tags.
- pSB1C3 has been replaced by pSB1C5

### CODE REVIEW

**Review by nickdelkis — COMMENTED** [review]
You added the genbank file in the iGEM_distribution folder and also the genbank file LOCUS name was not matching either the Data Source ID or (preferably) the Part Name.

I changed those up a bit (and remove the forbidden 6 at the start of the part) to make it work, and I think it will be fine now.

If the checks pass, no  missing seqs appear and everything is in pSB1C5, then we are good to go!

**Review by nickdelkis — APPROVED** [review]
Think it's fine now

**Comment by GC-repeat** [comment]
Sorry about that.

**Comment by nickdelkis** [comment]
No worries! It has to be a super cool collection.

**Pull request merged**
