### PR TITLE
Add flanking region test

### PR DESCRIPTION
**Pull request by vinoo-igem**
Test of adding flanking regions (BBa_D1005 + BBa_D1006) to create part insert for the Fluorescent Protein package. Also changed pSB1C3 to pSB1C5 to reflect that the flanking regions include the restriction sites.

### CODE REVIEW

**Comment by vinoo-igem** [comment]
@jakebeal I wanted to see the updated distribution.gb and distribution synthesis inserts fasta to make sure I had entered in flanking regions (as parts) correctly and they are correctly reflected in those files, but I'm guessing those aren't run for the pull request but updated once merged into develop?

**Comment by jakebeal** [comment]
They are run on the push request --- but appear to be failing right now, which is surprising to me. I'll look into it...

**Comment by jakebeal** [comment]
Found the problem: a bug in the SBOL3 to SBOL2 conversion that was exercised during conversion to GenBank. Working on patching it now.

**Review by jakebeal — APPROVED** [review]

**Comment by jakebeal** [comment]
I've got the build working and I see the flanking sequences in the FASTA exports. Please review and merge.

**Comment by vinoo-igem** [comment]
Have had a cursory look so far, and things are looking good with the fasta and gb files. But also a bug:

- The package name has been duplicated (likely added on top of the previous one) so we get things like this related to accession/versions:
"Fluorescent_Proteins_in_vector_Fluorescent_Proteins_in_vector_ins_BBa_E0020"
I'll open an issue for it.

**Comment by jakebeal** [comment]
Do please open that issue --- that's not so much a "bug" as a "stupid feature", but it should be easily corrected in any case.

**Comment by vinoo-igem** [comment]
@jakebeal My last commit either had a mistake and broke something or uncovered a bug...or both! The genbanks aren't being generated for the Fluorescent Reporter package for distribution.gb. 

1. Prior to my last commit, I had the Data Source ID for pSB1C5 as pSB1C3.
2. I changed Data Source ID for Part Name: pSB1C5 from pSB1C3 to pSB1C5. The name should was already correct on the Backbone field in the Library & Composites tab. I don't believe I changed anything else.

Notes
- The iGEM imports fasta file now includes pSB1C5
- Readme has gone from 1 vector to 0 vectors, presumably pSB1C3 read as a vector, but pSB1C5 doesn't?
- package.nt looks like it has lost a lot of the subcomponents for each construct, so maybe something isn't forming correctly here

Cleanup?
- iGEM_SBOL2_imports.nt, and package.nt hasn't removed pSB1C3

**Comment by jakebeal** [comment]
When it's imported as a FASTA (instead of as an SBOL file, like pSB1C3 could be), there's no type information available, and we aren't properly merging Excel and FASTA information right now.  This bumps up the priority of that issue.

You should also be able to work around it by deleting from the FASTA and adding a properly annotated GenBank or SBOL file for pSB1C3.

**Comment by vinoo-igem** [comment]
Ah, got it that makes sense, and now I remember that particular issue.

**Comment by vinoo-igem** [comment]
cleared out the various generated files in the package, but now there's an issue when retrieving parts. While it shows that all parts have an associated sequence, something is failing here: 

`Package specification contains 19 parts
Found 5 parts cached in package design files
 0 have sequences in Excel, 5 found in directory, 14 not found
 0 parts in directory are not used in package`

Also changed the data source for files like the pSB1C5.gb to be Local Sequence File, but that doesn't seem to have changed anything.

**Comment by jakebeal** [comment]
Looking in, it seems like it's choking on mCerulean for some reason, which I don't think that it should be. Can you please undelete NCBI_GenBank_imports.gb ? That should restore mCerulean to the cache and let it just grab the iGEM parts, which isn't a problem.

(the cache isn't updating right now because it's failing during the import process)

**Comment by vinoo-igem** [comment]
pSB1C5.gb is not getting recorded as a vector, so I'm guessing this is down to either the way Benchling exports a plasmid as a gb file, and/or the file not correctly identifying the role: plasmid.

**Comment by jakebeal** [comment]
I've looked into this, and there are two problems going on here:
1) There is nothing in the GenBank file that indicates that it is a vector, and
2) There is apparently _no_ standard way of indicating this information in GenBank format at all!

Given this, I think what needs to happen is to make a partial solution for #131 that will allow these issues to be resolved in the common case where role information is missing (and thus defaulting to `SO:engineered_region` in the conversion)

**Comment by vinoo-igem** [comment]
>     2. There is apparently _no_ standard way of indicating this information in GenBank format at all!

Yup, I was struggling to find this as well and then thought maybe to go backwards and figure out how the SBOL converter would convert a GenBank file for a vector.

**Comment by jakebeal** [comment]
The answer, unfortunately, is that since there isn't a "normal" way to indicate information about plasmids, the GenBank -> SBOL  converter simply gives up on the question.

The conversion of the iGEM database into SBOL on SynBioHub is _not_ GenBank -> SBOL, but instead is a specialized conversion from dumps of the old registry backend database format.

So instead I've set up a partial solution for #131 that addresses this common case. We'll see soon whether it's able to complete correctly.

**Comment by jakebeal** [comment]
Looks like the fix is working. @vinoo-igem , you should now be able to mark pSB1C5 it as a plasmid_vector in the Excel sheet and have the distribution use that information.

**Pull request merged**
