### PR TITLE
2022 release

### PR DESCRIPTION
**Pull request by vinoo-igem**
Handling of the 2022 Distribution Release

Several small changes still needed, and I'll document them here.

### CODE REVIEW

**Comment by vinoo-igem** [comment]
Just want to document some of the removals from the build plan.

- metal-sensing setting build to false #232
- 2A peptides setting build to false #236 
- removing duplicates from build in CRISPR-Cas #234

**Comment by jakebeal** [comment]
I've switched the target from `develop` to `main`, which is the branch intended for tagging releases on (see: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)

**Comment by jakebeal** [comment]
Yes, we'll want to merge into main and put the release tag on the branch once the final release is determined. I'm not sure whether it would be better to consider that release the order or the actual final version in FreeGenes. I'm thinking maybe the latter? Let's discuss on Slack and put the decision in #191

**Comment by jakebeal** [comment]
Summarizing plan from discussion on Slack:

1. merge into main as soon as the order it self has been placed
2. create a new release v1.0.0
3. When it exists at FreeGenes, update the packages to reflect what could / could not actually be included.
4. Make a new release branch for 1.0.1
5. Merge into main and release as 1.0.1
6. Repeat steps 3-5 as needed if things arrive at FreeGenes in multiple waves.

**Pull request merged**
