### PR TITLE
Open yeast collection

### PR DESCRIPTION
**Pull request by noahsprent**
- This package is an import of the existing Open Yeast Collection [that exists on FreeGenes](https://stanford.freegenes.org/collections/organismal-development-kits/products/open-yeast-toolkit#description). Any credit should go to Scott Pownall and Isaac Larkin. 
- The majority of sequences are missing here because they needed to be pulled from genbank files from freegenes, and this relies on #77 and #31. I added sequences manually for the parts for which the genbank files were missing. 
- There are 4 parts which are present here which freegenes does not currently have, according to the plate file (BBF10K_000059, BBF10K_000171, BBF10K_000264, BBF10K_000366). So we should be able to grab the majority of the physical samples from FreeGenes but then need to check on those four. 
- I have included all of the parts in the collection because they are designed to function as a kit. Even though some of them are e.g. E. coli origins and selection markers for constructing level 1 vectors that can be transformed into E. coli following assembly that may be present elsewhere in the distribution, they may not be compatible with the kit. The parts are MoClo compatible but use specific overhangs that might be different.

### CODE REVIEW

**Comment by jakebeal** [comment]
Do you want to ask a couple of other folks to look over your suggested part set as reviewers?

**Comment by noahsprent** [comment]
Ideal reviewers would be either Isaac Larkin or Scott Pownall, the original creators. I know that Isaac would be keen but as he's on a current iGEM team he isn't allowed to help. I can reach out to Scott.  Apart from that I don't know who on the current committee works on yeast, I'll ask.

**Comment by vinoo-igem** [comment]
This looks good to me! Shall I go ahead and merge pending @Sonjabillerbeck's review?

**Comment by jakebeal** [comment]
Yes, develop should be merged into it first to make sure it's up to date.

**Comment by jakebeal** [comment]
@vinoo-igem Let me know if you need help with the merge: it will have conflicts in the autogenerated files, and you can just resolve those by discarding changes since they will be regenerated after the merge in any case.

**Comment by vinoo-igem** [comment]
@jakebeal before I do something stupid: I wanted to double-check that the conflicts would be during the merging of the pull request into develop. Didn't get any conflicts merging develop into the feature and assumed the conflicts arise with newly autogened files in the feature vs whats in develop.

**Comment by jakebeal** [comment]
Looking at the diffs, that appears to be correct. You're clear to merge.

**Pull request merged**
