### PR TITLE
Create RBS Collection.xlsx

### PR DESCRIPTION
**Pull request by vignoni**
First attempt for RBS collection.
Closes issues #21 and #134 
Still needs more elements, but it incorporates the 20 most used RBSs in the registry.

### CODE REVIEW

**Comment by traci-igem** [comment]
I'll add in the BCDs to this as well this week.

**Comment by vinoo-igem** [comment]
Since there are so many variants for B0034, and we'll run into issues with spacing for Type IIS. Is there a preferred spacer/scar + AATG sequence?

**Comment by vignoni** [comment]
I don't know if preferred, but I have experience TACTAG A zworking more on less similarly to TACTAG.

**Review by jakebeal — APPROVED** [review]

**Comment by ethanj801** [comment]
Is there interest in adding RiboJ insulated versions of the B00XX series of RBSs? Speaking from personal experience (I was a member on both of the referenced works), these are fairly well characterized http://2016.igem.org/Team:William_and_Mary/RBS and RiboJ-B0034 was well as characterized with the entire Anderson promoter library https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6206723/.

**Comment by jakebeal** [comment]
@ethanj801 I think that's a great suggestion --- can you please open an issue for it? (and claim that issue if you want to do it yourself)

**Comment by ethanj801** [comment]
@jakebeal ok, issue created. I can claim it, but I think someone needs to assign it to me. Also, is there a structure yet for reporting quantitative measurements for parts? How do measurements get associated with parts?

**Pull request merged**
